[tool.poetry]
name = "Flask-Constance"
version = "0.1.0"
description = "Dynamic settings for Flask applications"
authors = ["Ivan Fedorov <inbox@titaniumhocker.ru>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
Flask = "^2.0.1"
flask-mongoengine = {version = "^1.0.0", optional = true, extras = ["mongoengine"]}
Flask-SQLAlchemy = {version = "^2.5.1", optional = true, extras = ["fsqla"]}
redis = {version = "^3.5.3", optional = true, extras = ["redis"]}
Flask-PyMongo = {version = "^2.3.0", optional = true, extras = ["pymongo"]}
peewee = {version = "^3.14.4", optional = true, extras = ["peewee"]}

[tool.poetry.dev-dependencies]
jedi = "^0.18.0"
mypy = "^0.910"
flake8 = "^3.9.2"
flake8-black = "^0.2.3"
black = "^21.7b0"
isort = "^5.9.3"
flake8-isort = "^4.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
