name: Codecov

env:
  CODECOV_TOKEN: 'b0643665-3115-40b0-a470-4f3739fe675e'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.4"

    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Tests with coverage
      run: |
        poetry run python -m pytest --cov
    - name: Upload coverage result to codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        files: ./.coverage
