name: Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"

    - name: Install poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: "1.1.4"

    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Tests with coverage
      run: |
        poetry run python -m pytest --cov
    - name: Upload coverage result to github
      run: |
        total=$(poetry run coverage report | grep TOTAL | awk '{print $4}' | awk -F% '{print $1}')
        if (( $(echo "$total <= 50" | bc -l) )) ; then
          COLOR=red
        elif (( $(echo "$total > 80" | bc -l) )); then
          COLOR=green
        else
          COLOR=orange
        fi
        curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
        gsutil  -h "Cache-Control: no-cache" cp badge.svg gs://${SOME_BUCKET}/${PROJECT_NAME}/codecov.svg
        gsutil acl ch -u AllUsers:R gs://${SOME_BUCKET}/${PROJECT_NAME}/codecov.svg
