name: mypy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install poetry
      uses: abatilo/actions-poetry@v2.1.6
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: Check types with mypy
      run: poetry run mypy --ignore-missing-imports flask_constance/
